// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpqcdrchuzrcgswfhmdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwcWNkcmNodXpyY2dzd2ZobWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzMjc5NDMsImV4cCI6MjA3ODkwMzk0M30.gbb86nMQQ3lnuYG6uDSXanZ6LCABqDEaBDNK5iBUzPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);