// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://goopwdwyvhpoqqerrqbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdvb3B3ZHd5dmhwb3FxZXJycWJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzI1NzMsImV4cCI6MjA2NDYwODU3M30.yjg8rOwEc8YvxaR7Ns6Ta5seqIqoc4QeGVmVTJLukAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);